// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjkdsndovpykswadsmcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdqa2RzbmRvdnB5a3N3YWRzbWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NjU4MjcsImV4cCI6MjA2MzA0MTgyN30.DvPb9i4EZ0-VCsjop2O1L-u4y15fhWwoXqXPNxTdOas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);